project:
  type: website
  output-dir: _site
  render:
    - "**/*.ipynb"
    - "**/*.md"
    - "**/*.qmd"

filters:
- marimo-team/marimo

website:
  title: "{{ graft_name }}"
  navbar:
    left:
      - href: index.qmd
        text: Overview
  sidebar:
    style: floating
    contents:
      - index.qmd
      - marimo_app.qmd

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
